export const STREAMER_ADDED = 'STREAMER_ADDED';
export const STREAMER_NAME = 'STREAMER_NAME';
export const TOGGLE_ADD_STREAMER_MODAL = 'TOGGLE_ADD_STREAMER_MODAL';
export const ADD_STREAMER_TO_STORE = 'ADD_STREAMER_TO_STORE';