export const STREAMER_ADDED = 'STREAMER_ADDED';
export const STREAMER_NAME = 'STREAMER_NAME';
export const TOGGLE_ADD_STREAMER_MODAL = 'TOGGLE_ADD_STREAMER_MODAL';
export const ADD_STREAMER_TO_LOCALSTORAGE = 'ADD_STREAMER_TO_LOCALSTORAGE';
export const TOGGLE_EDIT_STREAMER_MODAL = 'TOGGLE_EDIT_STREAMER_MODAL';
export const UPDATE_STREAMER_TO_STORE = 'UPDATE_STREAMER_TO_STORE';
export const UPDATE_STORE_TO_LOCALSTORAGE = 'UPDATE_STORE_TO_LOCALSTORAGE';
export const DELETE_STREAMER_FROM_STORE = 'DELETE_STREAMER_FROM_STORE';